# Generated by Django 5.2.7 on 2026-06-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='priority',
            field=models.CharField(choices=[('low', 'Низька'), ('medium', 'Середня'), ('high', 'Висока')], default='medium', max_length=50),
        ),
    ]
