# Generated by Django 5.2.7 on 2026-06-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0005_alter_complaint_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="complaint_photos/thumbnails/"
            ),
        ),
    ]
