# Generated by Django 5.2.7 on 2026-07-09 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0011_dormitorybuilding_commandant_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="building",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="residents",
                to="complaints.dormitorybuilding",
            ),
        ),
    ]
